worker_processes  1;
pid D:/CTXMv11/logs/nginx.pid;
error_log D:/CTXMv11/logs/error.log;

events {
    worker_connections  1024;
}

http {
    include       D:/nginx-1.29.8/conf/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    server_tokens off;

    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 5;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        image/svg+xml;

    client_body_temp_path D:/CTXMv11/temp/client_body;
    proxy_temp_path D:/CTXMv11/temp/proxy;
    fastcgi_temp_path D:/CTXMv11/temp/fastcgi;
    uwsgi_temp_path D:/CTXMv11/temp/uwsgi;
    scgi_temp_path D:/CTXMv11/temp/scgi;

    server {
        listen       8080;
        server_name  localhost;

        root   D:\CTXMv11;
        index  index.html;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /assets/ {
            expires 7d;
            add_header Cache-Control "public, max-age=604800";
        }

        error_page 404 /index.html;
    }
}
